---
- job:
    name: openstack-simple-stress-test
    nodeset: ubuntu-noble
    pre-run: playbooks/pre-test.yml
    run: playbooks/test.yml
    timeout: 14400
    roles:
      - zuul: osism/zuul-jobs
        name: devstack

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - flake8:
            nodeset: ubuntu-noble
        - mypy:
            nodeset: ubuntu-noble
        - openstack-simple-stress-test
        - python-black:
            nodeset: ubuntu-noble
        - yamllint:
            nodeset: ubuntu-noble
    periodic-daily:
      jobs:
        - flake8:
            nodeset: ubuntu-noble
        - mypy:
            nodeset: ubuntu-noble
        - openstack-simple-stress-test
        - python-black:
            nodeset: ubuntu-noble
        - yamllint:
            nodeset: ubuntu-noble
