---
- name: Stress test play
  hosts: all

  vars:
    zuul_work_dir: "{{ zuul.project.src_dir }}"

  roles:
    - role: tox
      vars:
        tox_extra_args: >-
          -- --cloud openstack --image cirros --flavor SCS-1V-2-5 --debug
          --no-wait --no-boot-volume --no-volume
    - role: tox
      vars:
        tox_extra_args: >-
          -- --cloud openstack --image cirros --flavor SCS-1V-2-5 --debug
          --no-wait --no-boot-volume --no-volume --mode block --number 4
          --parallel 2
    - role: tox
      vars:
        tox_extra_args: -- --cloud openstack --clean --yes
